### ISSUE TITLE
导包出现错误

### ISSUE THREAD

**Issue by KyrieXDL** [JunnYu/RoFormer_pytorch#1]
`from transformers.file_utils import ModelOutput, add_start_docstrings, add_start_docstrings_to_model_forward
ImportError: cannot import name 'add_start_docstrings_to_model_forward'`

请问出现这个错误是什么原因呢

**Comment by JunnYu** [comment]
> `from transformers.file_utils import ModelOutput, add_start_docstrings, add_start_docstrings_to_model_forward ImportError: cannot import name 'add_start_docstrings_to_model_forward'`
> 
> 请问出现这个错误是什么原因呢

建议更新transformers库

**Comment by KyrieXDL** [comment]
> > `from transformers.file_utils import ModelOutput, add_start_docstrings, add_start_docstrings_to_model_forward ImportError: cannot import name 'add_start_docstrings_to_model_forward'`
> > 请问出现这个错误是什么原因呢
> 
> 建议更新transformers库,你的版本可能太低, pip install -U transformers
博主你好，请问你的transformers版本是多少呢，我直接升级到最新版会和一些已有的包版本冲突

**Comment by JunnYu** [comment]
@KyrieXDL 那就你手动把src/roformer/modeling_roformer.py中的有关add_start_docstrings_to_model_forward代码删掉，顺便问下你的transformers什么版本？

**Comment by KyrieXDL** [comment]
> @KyrieXDL 那就你手动把src/roformer/modeling_roformer.py中的有关add_start_docstrings_to_model_forward代码删掉，顺便问下你的transformers什么版本？

我目前用的3.4.0的版本

**Comment by KyrieXDL** [comment]
非常感谢，我升级到3.5.1已经解决了，我看到transformers官方文档中3.4.0的版本有api还不支持
