### ISSUE TITLE
HF RoFormerTokenizerFast  offset_mapping实现上似乎有点问题

### ISSUE THREAD

**Issue by heyouxin** [JunnYu/RoFormer_pytorch#10]
b = '第三，预计负债的确认和计提在很大程度上依赖于管理层的判断。第三，值得注意的是我们应当重视财务的健康程度。第五，要提高从业人员的素质。'

b_token = tokenizer([b], return_offsets_mapping=True)

{'input_ids': [[101, 27211, 5661, 34194, 31032, 3399, 26510, 873, 30425, 1101, 17817, 26940, 198, 404, 4769, 271, 41334, 3399, 10907, 179, 27211, 5661, 44272, 3399, 2274, 18578, 17228, 32861, 31051, 3399, 9395, 26940, 179, 27214, 5661, 4566, 19776, 44131, 3399, 27528, 179, 102]], 'token_type_ids': [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], 'offset_mapping': [[(0, 0), (0, 2), (0, 1), (0, 2), (0, 2), (0, 1), (0, 2), (0, 1), (0, 2), (0, 1), (0, 2), (0, 2), (0, 1), (0, 1), (0, 1), (0, 1), (0, 3), (0, 1), (0, 2), (0, 1), (0, 2), (0, 1), (0, 4), (0, 1), (0, 1), (0, 2), (0, 2), (0, 2), (0, 2), (0, 1), (0, 2), (0, 2), (0, 1), (0, 2), (0, 1), (0, 1), (0, 2), (0, 4), (0, 1), (0, 2), (0, 1), (0, 0)]]}

这里offset长度是正确的，索引没了。

**Comment by JunnYu** [comment]
https://github.com/huggingface/transformers/issues/12244

同样的问题，如果使用char level的模型，那就直接使用bert的分词器就可以了，如果是使用word level的模型，那就照着我的链接修改一下就行。我注释中介绍了两者的区别，一个是速度快但是offset map不对，另一个是速度慢但是offset map 正确。

**Comment by heyouxin** [comment]
> [huggingface/transformers#12244](https://github.com/huggingface/transformers/issues/12244)
> 
> 同样的问题，如果使用chat level的模型，那就直接使用bert的分词器就可以了，如果是使用word level的模型，那就照着我的链接修改一下就行。我注释中介绍了两者的区别，一个是速度快但是offset map不对，另一个是速度慢但是offset map 正确。

好的，这个长度是对的，遍历一遍，也很容易得到正确的offset mapping
