### ISSUE TITLE
'RoFormerModel' object has no attribute 'shape'

### ISSUE THREAD

**Issue by CurisZhou** [JunnYu/RoFormer_pytorch#11]
大佬，我用这个convert_tf_checkpoint_to_pytorch()函数想将苏神最近开源的RoFormer-Sim模型转成pytorch版的，但是遇到了torch.nn.modules.module.ModuleAttributeError: 'RoFormerModel' object has no attribute 'shape'的问题：

def convert_tf_checkpoint_to_pytorch(tf_checkpoint_path, roformer_config_file, pytorch_dump_path):

    # Initialise PyTorch model
    config = RoFormerConfig.from_json_file(roformer_config_file)
    print(f"Building PyTorch model from configuration: {config}")
    model = RoFormerForMaskedLM(config)

    # Load weights from tf checkpoint
    load_tf_weights_in_roformer(model, config, tf_checkpoint_path)

    # Save pytorch-model
    print(f"Save PyTorch model to {pytorch_dump_path}")
    torch.save(model.state_dict(), pytorch_dump_path, _use_new_zipfile_serialization=False)

Traceback (most recent call last):
  File "D:/Python/3.代码储存/1.重要代码学习笔记(重要)/21.Python自然语言处理/18.预训练语言模型专题学习/将tf1的checkpoint模型权重转换为pytorch的模型权重/convert_tf_to_pytorch.py", line 81, in <module>
    pytorch_dump_path)
  File "D:/Python/3.代码储存/1.重要代码学习笔记(重要)/21.Python自然语言处理/18.预训练语言模型专题学习/将tf1的checkpoint模型权重转换为pytorch的模型权重/convert_tf_to_pytorch.py", line 42, in convert_tf_checkpoint_to_pytorch_roformer_model
    load_tf_weights_in_roformer(model, config, tf_checkpoint_path)
  File "D:\Python\main\lib\site-packages\transformers\models\roformer\modeling_roformer.py", line 167, in load_tf_weights_in_roformer
    pointer.shape == array.shape
  File "D:\Python\main\lib\site-packages\torch\nn\modules\module.py", line 779, in __getattr__
    type(self).__name__, name))
torch.nn.modules.module.ModuleAttributeError: 'RoFormerModel' object has no attribute 'shape'

我使用的transformers版本是4.8.2的，函数里的RoFormerForMaskedLM模型换成RoFormerForCausalLM、RoFormerPreTrainedModel也不行依然会报错。

RoFormer-Sim模型的权重下载自苏神的github: https://github.com/ZhuiyiTechnology/roformer/blob/main/README_zh.md

**Comment by CurisZhou** [comment]
ps: 在https://github.com/huggingface/transformers/issues/393这个issue下找到了别人转Bert模型遇到了相同的这个问题，我试试看能不能解决。

**Comment by CurisZhou** [comment]
ps: 在https://github.com/huggingface/transformers/issues/393   这个issue下找到了别人转Bert模型遇到了相同的这个问题，我试试看能不能解决。

**Comment by JunnYu** [comment]
@CurisZhou 主要原因是我当前的代码里面没有加pooler部分。等我改一下代码吧

**Comment by JunnYu** [comment]
@CurisZhou 
现在安装最新的本仓库代码`pip install git+https://github.com/JunnYu/RoFormer_pytorch.git` ，然后转换权重
``` python
from roformer.convert_roformer_original_tf_checkpoint_to_pytorch import (
    convert_tf_checkpoint_to_pytorch,
)

tf_checkpoint_path = "chinese_roformer-sim-char_L-12_H-768_A-12/bert_model.ckpt"
bert_config_file = "chinese_roformer-sim-char_L-12_H-768_A-12/bert_config.json"
pytorch_dump_path = "roformer_chinese_sim_char_base/pytorch_model.bin"
convert_tf_checkpoint_to_pytorch(
    tf_checkpoint_path, bert_config_file, pytorch_dump_path
)

```

使用的时候如果想要用到pooler部分的权重，那么你需要使用本仓库的代码（本仓库代码添加了pooler部分）。
如果不需要使用pooler部分权重，那你可以用huggingface仓库的transformers库加载。（只不过使用这个加载会缺少pooler部分，因为模型没添加pooler部分）

这个是我转换过的权重，最大长度是512的
- https://huggingface.co/junnyu/roformer_chinese_sim_char_base

![image](https://user-images.githubusercontent.com/50394665/125093505-f024e280-e104-11eb-8c84-0077a345daa2.png)

**Comment by CurisZhou** [comment]
好嘞 感谢大佬！

**Comment by CurisZhou** [comment]
@JunnYu 好嘞 感谢大佬！

**Comment by BigBen7** [comment]
大佬，我是用你的方法转化还是报错了
Traceback (most recent call last):
  File "convert_roformer_original_tf_checkpoint_to_pytorch.py", line 76, in <module>
    args.tf_checkpoint_path, args.bert_config_file, args.pytorch_dump_path
  File "convert_roformer_original_tf_checkpoint_to_pytorch.py", line 36, in convert_tf_checkpoint_to_pytorch
    load_tf_weights_in_roformer(model, config, tf_checkpoint_path)
  File "/opt/huawei/anaconda3/envs/tf1.15/lib/python3.6/site-packages/roformer/modeling_roformer.py", line 185, in load_tf_weights_in_roformer
    pointer.shape == array.shape
AttributeError: 'NoneType' object has no attribute 'shape'

> @CurisZhou 现在安装最新的本仓库代码`pip install git+https://github.com/JunnYu/RoFormer_pytorch.git` ，然后转换权重
> 
> ```python
> from roformer.convert_roformer_original_tf_checkpoint_to_pytorch import (
>     convert_tf_checkpoint_to_pytorch,
> )
> 
> tf_checkpoint_path = "chinese_roformer-sim-char_L-12_H-768_A-12/bert_model.ckpt"
> bert_config_file = "chinese_roformer-sim-char_L-12_H-768_A-12/bert_config.json"
> pytorch_dump_path = "roformer_chinese_sim_char_base/pytorch_model.bin"
> convert_tf_checkpoint_to_pytorch(
>     tf_checkpoint_path, bert_config_file, pytorch_dump_path
> )
> ```
> 
> 使用的时候如果想要用到pooler部分的权重，那么你需要使用本仓库的代码（本仓库代码添加了pooler部分）。 如果不需要使用pooler部分权重，那你可以用huggingface仓库的transformers库加载。（只不过使用这个加载会缺少pooler部分，因为模型没添加pooler部分）
> 
> 这个是我转换过的权重，最大长度是512的
> 
> * https://huggingface.co/junnyu/roformer_chinese_sim_char_base
> 
> ![image](https://user-images.githubusercontent.com/50394665/125093505-f024e280-e104-11eb-8c84-0077a345daa2.png)



> @CurisZhou 现在安装最新的本仓库代码`pip install git+https://github.com/JunnYu/RoFormer_pytorch.git` ，然后转换权重
> 
> ```python
> from roformer.convert_roformer_original_tf_checkpoint_to_pytorch import (
>     convert_tf_checkpoint_to_pytorch,
> )
> 
> tf_checkpoint_path = "chinese_roformer-sim-char_L-12_H-768_A-12/bert_model.ckpt"
> bert_config_file = "chinese_roformer-sim-char_L-12_H-768_A-12/bert_config.json"
> pytorch_dump_path = "roformer_chinese_sim_char_base/pytorch_model.bin"
> convert_tf_checkpoint_to_pytorch(
>     tf_checkpoint_path, bert_config_file, pytorch_dump_path
> )
> ```
> 
> 使用的时候如果想要用到pooler部分的权重，那么你需要使用本仓库的代码（本仓库代码添加了pooler部分）。 如果不需要使用pooler部分权重，那你可以用huggingface仓库的transformers库加载。（只不过使用这个加载会缺少pooler部分，因为模型没添加pooler部分）
> 
> 这个是我转换过的权重，最大长度是512的
> 
> * https://huggingface.co/junnyu/roformer_chinese_sim_char_base
> 
> ![image](https://user-images.githubusercontent.com/50394665/125093505-f024e280-e104-11eb-8c84-0077a345daa2.png)
