### ISSUE TITLE
请问可以直接输入几千字的超长文本吗？

### ISSUE THREAD

**Issue by geolvr** [JunnYu/RoFormer_pytorch#15]

**Comment by JunnYu** [comment]
`roformer_chinese_base`是word版本的模型，它支持最大长度是1536，你当然可以自己修改一下这里，改成你要的长度（虽然没有预训练到超过1536长度的文本，不过可以试试）
https://github.com/JunnYu/RoFormer_pytorch/blob/6f0c0b67780bcfc6f0d9a7efae11e7a485b6e676/src/roformer/configuration_roformer.py#L66

注意： 如果碰到权重不匹配的问题，大概率是因为模型加载了固定的最大位置编码，要想修改错误，那就删除pytorch_model.bin中关于`embed_positions `的权重。https://github.com/JunnYu/RoFormer_pytorch/blob/6f0c0b67780bcfc6f0d9a7efae11e7a485b6e676/src/roformer/modeling_roformer.py#L605-L608
