### ISSUE TITLE
使用这个方法转化依旧报了类似错误，具体信息如下@CurisZhou

### ISSUE THREAD

**Issue by BigBen7** [JunnYu/RoFormer_pytorch#18]
大佬，我是用你的方法转化还是报错了
Traceback (most recent call last):
  File "convert_roformer_original_tf_checkpoint_to_pytorch.py", line 76, in <module>
    args.tf_checkpoint_path, args.bert_config_file, args.pytorch_dump_path
  File "convert_roformer_original_tf_checkpoint_to_pytorch.py", line 36, in convert_tf_checkpoint_to_pytorch
    load_tf_weights_in_roformer(model, config, tf_checkpoint_path)
  File "/opt/huawei/anaconda3/envs/tf1.15/lib/python3.6/site-packages/roformer/modeling_roformer.py", line 185, in load_tf_weights_in_roformer
    pointer.shape == array.shape
AttributeError: 'NoneType' object has no attribute 'shape'

@CurisZhou 
现在安装最新的本仓库代码`pip install git+https://github.com/JunnYu/RoFormer_pytorch.git` ，然后转换权重
``` python
from roformer.convert_roformer_original_tf_checkpoint_to_pytorch import (
    convert_tf_checkpoint_to_pytorch,
)

tf_checkpoint_path = "chinese_roformer-sim-char_L-12_H-768_A-12/bert_model.ckpt"
bert_config_file = "chinese_roformer-sim-char_L-12_H-768_A-12/bert_config.json"
pytorch_dump_path = "roformer_chinese_sim_char_base/pytorch_model.bin"
convert_tf_checkpoint_to_pytorch(
    tf_checkpoint_path, bert_config_file, pytorch_dump_path
)

```

使用的时候如果想要用到pooler部分的权重，那么你需要使用本仓库的代码（本仓库代码添加了pooler部分）。
如果不需要使用pooler部分权重，那你可以用huggingface仓库的transformers库加载。（只不过使用这个加载会缺少pooler部分，因为模型没添加pooler部分）

这个是我转换过的权重，最大长度是512的
- https://huggingface.co/junnyu/roformer_chinese_sim_char_base

![image](https://user-images.githubusercontent.com/50394665/125093505-f024e280-e104-11eb-8c84-0077a345daa2.png)

_Originally posted by @JunnYu in https://github.com/JunnYu/RoFormer_pytorch/issues/11#issuecomment-877102272_

**Comment by JunnYu** [comment]
出错的原因是`self.pooler等于None了`。
原先`RoFormerForMaskedLM` 默认值` self.roformer = RoFormerModel(config, add_pooling_layer=False)`
现在已经更新过了` self.roformer = RoFormerModel(config, add_pooling_layer=True)`
可以按照之前的方法就可以成功转换了。
![image](https://user-images.githubusercontent.com/50394665/144390508-12d56c7c-c109-4c1a-92e8-b564535e469c.png)

**Comment by CurisZhou** [comment]
感谢大佬😄



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yujun ***@***.***&gt;
发送时间: 2021年12月2日 17:01
收件人: JunnYu/RoFormer_pytorch ***@***.***&gt;
抄送: CurisZhou ***@***.***&gt;, Mention ***@***.***&gt;
主题: 回复：[JunnYu/RoFormer_pytorch] ***@***.*** (Issue #18)
