### ISSUE TITLE
使用huggingface模型

### ISSUE THREAD

**Issue by insist93** [JunnYu/RoFormer_pytorch#19]
大佬，我用你的示例代码
import torch
from transformers import RoFormerModel, RoFormerTokenizer, TFRoFormerModel

tokenizer = RoFormerTokenizer.from_pretrained("junnyu/roformer_chinese_sim_char_ft_base")
pt_model = RoFormerModel.from_pretrained("junnyu/roformer_chinese_sim_char_ft_base")
text = "这里基本保留了唐宋遗留下来的坊巷格局和大量明清古建筑，其中各级文保单位29处，被誉为“里坊制度的活化石”“明清建筑博物馆”！"
pt_inputs = tokenizer(text, return_tensors="pt")
with torch.no_grad():
    pt_outputs = pt_model(**pt_inputs).last_hidden_state
print(pt_outputs.shape)

输出shape是(1,63,768)，如果我想获得和苏神 tf 版本roformer的predict结果，是直接取pt_outputs[0][0]吗？还是应该做其他操作？

**Comment by JunnYu** [comment]
### 这里加载的是`RoFormerForMaskedLM`
```python
from roformer import RoFormerForMaskedLM,RoFormerTokenizer
tokenizer = RoFormerTokenizer.from_pretrained("junnyu/roformer_chinese_sim_char_base")
model = RoFormerForMaskedLM.from_pretrained("junnyu/roformer_chinese_sim_char_base")
model.eval()
inputs = tokenizer(["今天是个好日子","我想出去玩"],return_tensors="pt",padding=True)
outputs = model(**inputs,return_dict=False)
# masked lm score
print(outputs[0].shape)
# torch.Size([2, 9, 12000])
# pooler output
print(outputs[1].shape)
# torch.Size([2, 768])
```
我猜你想要的是 `pooler_output` torch.Size([2, 768])

### 这里加载的是`RoFormerModel`
```python
from roformer import RoFormerModel,RoFormerTokenizer
tokenizer = RoFormerTokenizer.from_pretrained("junnyu/roformer_chinese_sim_char_base")
model = RoFormerModel.from_pretrained("junnyu/roformer_chinese_sim_char_base")
model.eval()
inputs = tokenizer(["今天是个好日子","我想出去玩"],return_tensors="pt",padding=True)
outputs = model(**inputs)
# pooler_output
print(outputs.pooler_output.shape)
# torch.Size([2, 768])
```
我猜你想要的是 `pooler_output` torch.Size([2, 768])


记得安装使用本仓库的代码！
`pip install git+https://github.com/JunnYu/RoFormer_pytorch`

**Comment by insist93** [comment]
Traceback (most recent call last):
  File "D:/05_github_demo/roformer/main.py", line 1, in <module>
    from roformer import RoFormerModel, RoFormerTokenizer
  File "<frozen importlib._bootstrap>", line 1020, in _handle_fromlist
  File "D:\05_github_demo\roformer\venv\lib\site-packages\transformers\file_utils.py", line 2140, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "D:\05_github_demo\roformer\venv\lib\site-packages\transformers\file_utils.py", line 2154, in _get_module
    ) from e
RuntimeError: Failed to import roformer.modeling_roformer because of the following error (look up to see its traceback):
**add_code_sample_docstrings() got an unexpected keyword argument 'tokenizer_class'**

直接pip install roformer，默认安装最新的transformer==4.12.5会出现以上bug，换到4.9.1可以了。
比对了encode结果基本一致，感谢大佬。

**Comment by AlphaNext** [comment]
maybe [this solution](https://github.com/openai/gpt-2/issues/299#issuecomment-1150012753) will be available 


change the variable name ```tokenizer_class``` to ```processor_class```
