### ISSUE TITLE
手动转换权重有问题

### ISSUE THREAD

**Issue by TestNLP** [JunnYu/RoFormer_pytorch#23]
python convert_roformer_original_tf_checkpoint_to_pytorch.py \
    --tf_checkpoint_path=xxxxxx/chinese_roformer_L-12_H-768_A-12/bert_model.ckpt \
    --roformer_config_file=pretrained_models/chinese_roformer_base/config.json \
    --pytorch_dump_path=pretrained_models/chinese_roformer_base/pytorch_model.bin

这个直接运行好像不行，按照错误提示修改以后，只生成了一个pb文件，没有对应的config文件，这个是为啥呢？

**Comment by TestNLP** [comment]
计算出来的结果和原本tensorflow的不一样

**Comment by JunnYu** [comment]
贴个图？还有错误提示？pytorch的config文件需要自己进行修改，参考huggingface.co已有的例子进行修改

**Comment by TestNLP** [comment]
没有错误提示

**Comment by TestNLP** [comment]
转的过程都是ok的，没有任何报错，就是pytorch版本和tensorflow版本算出来的结果不一样

**Comment by TestNLP** [comment]
![image](https://user-images.githubusercontent.com/23632648/147751143-7b355d69-17a2-4e94-b1cd-446b6020bda7.png)

**Comment by TestNLP** [comment]
这个是转完以后，打印出来的config，我之前没看到，我刚才把这个拷贝到config文件中，是可以跑起来了，只是算的结果怎么不一样呢

**Comment by JunnYu** [comment]
结果应该一样，我刚刚尝试了转换权重的代码。你的是char版本的模型还是word版本的模型，本仓库的tokenizer是word版本的。
![image](https://user-images.githubusercontent.com/50394665/147751705-effead48-f043-4196-8e08-1255c8f095f7.png)

**Comment by TestNLP** [comment]
我的是char，这个怎么改成char版本？

**Comment by JunnYu** [comment]
权重转换是一样的，`char`版本的`tokenizer`直接调用`BertTokenizer`就可以了

**Comment by TestNLP** [comment]
是直接改convert_roformer_original_tf_checkpoint_to_pytorch.py里边的代码吗

**Comment by TestNLP** [comment]
具体在哪修改，能否贴一个图出来呢，感谢

**Comment by JunnYu** [comment]
char和word转换权重的代码是一样的！主要区别是你使用的时候使用的tokenizer的区别。

## char版本的模型调用
```python
from roformer import RoFormerModel
from transformers import BertTokenizer
model = RoFormerModel.from_pretrained("模型权重文件夹")
tokenizer = BertTokenizer.from_pretrained("模型权重文件夹")
```

## word版本的模型调用
```python
from roformer import RoFormerModel, RoFormerTokenizer
model = RoFormerModel.from_pretrained("模型权重文件夹")
tokenizer = RoFormerTokenizer.from_pretrained("模型权重文件夹")
```

**Comment by TestNLP** [comment]
好的，感谢解答，您的工作非常棒，能否加一个微信，18392408198
