### ISSUE TITLE
Roformer导出onnx

### ISSUE THREAD

**Issue by mudong0419** [JunnYu/RoFormer_pytorch#24]
请问怎么将Roformer导出成onnx格式，然后用onnxruntime进行推理呢？

**Comment by JunnYu** [comment]
## 参考huggingface的transformers
https://github.com/huggingface/transformers/blob/master/docs/source/serialization.mdx

修改文件[transformers/onnx/converter.py](https://github.com/huggingface/transformers/blob/master/src/transformers/onnx/features.py)
![image](https://user-images.githubusercontent.com/50394665/150064706-893adb38-8a06-4b05-a82f-59917bf51dc8.png)

```python
        "roformer": supported_features_mapping(
            "default",
            "masked-lm",
            "sequence-classification",
            "token-classification",
            "question-answering",
            onnx_config_cls=BertOnnxConfig,
        ),
```
然后进行这个
```sh
python -m transformers.onnx --model=junnyu/roformer_chinese_base --feature masked-lm onnx/ --atol 1e-4
```
![image](https://user-images.githubusercontent.com/50394665/150064477-af327f6b-ee80-4c59-91fd-9e2cf6faa86d.png)

```python
from transformers import AutoTokenizer
from onnxruntime import InferenceSession
import torch
tokenizer = AutoTokenizer.from_pretrained("junnyu/roformer_chinese_base")
session = InferenceSession("onnx/model.onnx")
inputs = tokenizer("今天[MASK]非常好，我想出去玩！", return_tensors="np")
outputs = session.run(output_names=["logits"], input_feed=dict(inputs))
tokenizer.decode(torch.from_numpy(outputs[0][0][2]).argmax())
```
![image](https://user-images.githubusercontent.com/50394665/150064495-6a68b38c-5cad-4c9e-b8db-4c9936dbeeaf.png)

**Comment by mudong0419** [comment]
谢谢您的详尽回复，如果我是想计算句子向量呢？用onnxruntime提供句子向量服务。

**Comment by JunnYu** [comment]
这里
![image](https://user-images.githubusercontent.com/50394665/150116998-c209a86e-91f3-43a8-9a9d-3c64840bd021.png)

**Comment by mudong0419** [comment]
谢谢您的建议，我只要是希望能拿到pool层的output，transformers里的RoformerModel没有pooler，我自己改了后，导出onnx文件，但是推理速度比pytorch没有太大提升，特别是长一点的句子反而更慢了。另外，发现pytorch版的roformer比苏神的tensorflow版推理速度慢了1/3左右，不知道您有没有比较过onnx版本和tensorflow版本的推理速度。

**Comment by mudong0419** [comment]
![image](https://user-images.githubusercontent.com/24379054/150504488-7661399a-4a92-44b7-a38b-9d19526d8a05.png)
是我环境的问题，已经解决。做了一个对比，onnxruntime还是有明显优势的。
