### ISSUE TITLE
BertTokenizer和RoformerTokenizer的区别？

### ISSUE THREAD

**Issue by Yi-Shi94** [JunnYu/RoFormer_pytorch#28]
为什么有的时候使用前者，有时使用后者呢？

**Comment by VolantBoy** [comment]
> 为什么有的时候使用前者，有时使用后者呢？

请问您知道为啥了嘛

**Comment by JunnYu** [comment]
一个是char级别的tokenizer，一个是使用了jieba预先分词后的word级别的tokenizer

**Comment by JunnYu** [comment]
如果模型带char这个名字，就证明是char级别。可以直接使用BertTokenizer，我看目前几乎所有中文预训练模型都用的是char级别的BertTokenizer
