### ISSUE TITLE
使用roformer_chinese_sim_char_ft_xxx模型在自己的句对上fine-tune，做相似度任务

### ISSUE THREAD

**Issue by Yi-Shi94** [JunnYu/RoFormer_pytorch#29]
按照https://kexue.fm/archives/8541 ，“具体来说，Sentence-BERT是将u,v,|u−v|（其中|u−v|是指u−v的每个元素都取绝对值后构成的向量）拼接起来做为特征，后面接一个全连接层做2分类。”
我想确认下，这个全连接层的权重苏神是不是没有提供？

**Comment by JunnYu** [comment]
你可以下载原本的tf权重打开看一下有没有这个dense的权重，我看代码最终进行了5分类。你可以确定下有没有这部分权重（我使用的转换脚本不会转换这些权重的，因为模型没有这分类的全连接层，故无法加载这些权重，最终也就不会保存这分类的权重）

**Comment by Yi-Shi94** [comment]
ok谢谢
