### ISSUE TITLE
ValueError: tensorflow.__spec__ is None

### ISSUE THREAD

**Issue by zmh908264302** [JunnYu/RoFormer_pytorch#3]
请问为啥必须
```
import roformer
import bert4keras
```
而导包顺序反过来就如题错误

**Comment by JunnYu** [comment]
@zmh908264302 我这两个顺序都可以啊
![image](https://user-images.githubusercontent.com/50394665/116352928-7fba3500-a828-11eb-8abd-f72da093d852.png)

**Comment by zmh908264302** [comment]
猜测是不是版本的问题，我现在cuda10，最高可用torch=1.4。并且还需要利用torch 1.7转换一下，不然会有错误如https://blog.csdn.net/qxqxqzzz/article/details/110955978

**Comment by SeanLiaoy** [comment]
有同样的问题，torch=1.3.1，下载转换好的pytorch权重无法正确加载模型，
执行：
`RoFormerModel.from_pretrained("./roformer_chinese_base", from_tf=False)`
显示错误如下：
> OSError: Unable to load weights from pytorch checkpoint file for './roformer_chinese_base' at './roformer_chinese_base/pytorch_model.bin'If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True. 

甚至不指定from_tf=False的情况下会默认当成是tensorflow权重

**Comment by JunnYu** [comment]
@SeanLiaoy 
参考这个
https://pytorch.org/docs/stable/generated/torch.save.html
**The 1.6 release of PyTorch switched torch.save to use a new zipfile-based file format. torch.load still retains the ability to load files in the old format. If for any reason you want torch.save to use the old format, pass the kwarg _use_new_zipfile_serialization=False.**
我保存权重的时候使用的是pytorch1.6+。
因此，你有两种选择，一是更新pytorch，二是在你的torch=1.3.1环境下，下载原版tf权重，然后使用代码https://github.com/JunnYu/RoFormer_pytorch/blob/main/convert_roformer_original_tf_checkpoint_to_pytorch.py
转化权重。

**Comment by JunnYu** [comment]
@SeanLiaoy @SeanLiaoy 我现在已经更新过权重了，现在可以pytorch<1.6的也可以直接加载权重了。
```python
model = RoFormerForMaskedLM.from_pretrained("junnyu/roformer_chinese_base") #从https://huggingface.co/junnyu/roformer_chinese_base自动下载
```
或者使用转化过的权重，链接：https://pan.baidu.com/s/10W5BYDQSeLyajTWjexZeoQ 提取码：bimr

**Comment by SeanLiaoy** [comment]
It works~
