### ISSUE TITLE
关于rotary_value的问题

### ISSUE THREAD

**Issue by hxs91** [JunnYu/RoFormer_pytorch#34]
我看到不管是现在的实现还是以前的实现，rotary_value为false的时候，对于q和k都会做改变，我不清楚这和完全不做（将rotary_value为false时的代码都注释掉）改变是否等价？至少从实验结果来看差距很多。另外如果单纯将rotary_value设置为false的时候，效果比true的时候还要好一些。

任务为预训练，并且在下游任务上进行微调。比较了预训练时训练loss和验证loss，微调时不同任务的得分。

**Comment by JunnYu** [comment]
rotary_value主要判断是否对value_layer进行rotary，False表示不旋转。
苏神的预训练的时候并未对value_layer进行rotary（也就是只rotary了query和key）。
rotary_value主要是给自己用的，自己用electra的方式训练了个roformer_small （https://huggingface.co/junnyu/roformer_small_discriminator）

**Comment by hxs91** [comment]
@JunnYu 嗯，看代码的确是这样，但我之前不确定False之后是不是在后边的运算中会等价（原谅我没有太去深究原理），我又做了几个实验（实验主体为文本生成预训练+三个下游任务的微调），结论如下：
1. 相比于绝对位置编码，旋转位置编码效果提升非常明显。
2. 目前看只rotary query和key的效果好于同时对于value进行rotary（v1和v2两个版本的结论都是如此）。
3. v1和v2的结果差距不大。

再次感谢你的工作~
