### ISSUE TITLE
Roformer-sim生成相似句乱码

### ISSUE THREAD

**Issue by ann22** [JunnYu/RoFormer_pytorch#37]
chinese_roformer-v2-char_L-12_H-768_A-12模型转成torch模型后，加载生成的相似句如下

![image](https://user-images.githubusercontent.com/28564507/177243860-e57a8d05-9bac-4315-b692-9b837ecd065b.png)

**Comment by JunnYu** [comment]
这个模型又没有进行生成式的训练，输出结果当然不对。
目前只有含有sim的预训练权重才能正常输出结果。

**Comment by ann22** [comment]
> 这个模型又没有进行生成式的训练，输出结果当然不对。 目前只有含有sim的预训练权重才能正常输出结果。

好的，谢谢
