### ISSUE TITLE
roformer-v2结合huggingface的库accelerate 使用时会导致保存的模型被多次删除；导致部分模型没有被保存

### ISSUE THREAD

**Issue by XiaoqingNLP** [JunnYu/RoFormer_pytorch#38]
accelerate的保存模型方法：
```
# How to save your 🤗 Transformer?
accelerator.wait_for_everyone()
unwrapped_model = accelerator.unwrap_model(model)
unwrapped_model.save_pretrained(save_dir, save_function=accelerator.save, state_dict=accelerator.get_state_dict(model))
```

roformer-v1 没有这个问题；roformer-v2 有这个问题，删除了多次

**Comment by JunnYu** [comment]
不应该会有这个问题吧，因为两个模型都是在一个代码里面，我看这里都是这么保存的呀。
https://github.com/huggingface/transformers/blob/5d1fed0740ec03ad45032f353379784d41c7118a/examples/pytorch/text-classification/run_glue_no_trainer.py#L580

**Comment by XiaoqingNLP** [comment]
@JunnYu  v1 没有这个问题，v2有，所以大概率这不是accelerate的问题
我之前v1 是直接从transformers里面import的，v2是按readme里面import的，我觉得这个可能是导致这个问题的差异。
最近比较忙，我用一个直接的方法解决这个问题了，我把这个问题po出来探讨一下
