### ISSUE TITLE
cpkt转换为bin出错

### ISSUE THREAD

**Issue by KyrieXDL** [JunnYu/RoFormer_pytorch#4]
博主你好，我用苏神的roformer预训练代码在任务数据集上继续预训练，然后保存为ckpt的格式，然后用你的pytorch转换格式的时候报了这个错误，请问博主知道什么原因吗
AttributeError: 'RoFormerForPreTraining' object has no attribute 'bias'

**Comment by JunnYu** [comment]
@KyrieXDL 你可以检查一下，你的预训练ckpt文件中权重名字，是不是跟苏神的训练出来的权重名字一样。

**Comment by KyrieXDL** [comment]
> @KyrieXDL 你可以检查一下，你的预训练ckpt文件中权重名字，是不是跟苏神的训练出来的权重名字一样，感觉你的代码可能多生成了啥权重。
> 
> ```python
> import os
> import tensorflow as tf
> tf_path = os.path.abspath(tf_checkpoint_path)
> # Load weights from TF model
> init_vars = tf.train.list_variables(tf_path)
> for name, shape in init_vars:
>     print(name)
> ```
> 
> 我这个加载权重的时候，使用的就是bert的转化代码，只是改了个名字，把bert改成了roformer。

感谢大佬，解决了，我保存模型的时候用的是：
`saver = tf.train.Saver()
model = keras.models.load_model("model.h5")
sess = keras.backend.get_session()
save_path = saver.save(sess, "/tmp/model.ckpt")`
但是苏神的transformer模型类提供了save_weights_as_checkpoint函数，用这个保存就正确了。
