### ISSUE TITLE
有计划让模型上线huggingface / transformers吗

### ISSUE THREAD

**Issue by huhk-sysu** [JunnYu/RoFormer_pytorch#5]
您好！

请问Roformer模型有可能加入huggingface/transformers的模型列表中吗？我看您提供的API与其很相似，是否有相关计划？

谢谢！

**Comment by JunnYu** [comment]
@huhk-sysu 目前已经提交了个pr到huggingface的transformers仓库了
https://github.com/huggingface/transformers/pull/11684
