### ISSUE TITLE
Huggingface代码最大序列长度问题

### ISSUE THREAD

**Issue by zyccyz** [JunnYu/RoFormer_pytorch#9]
似乎使用huggingface的时候最大序列长度无法超过512，这是否与max_position_embeddings这个超参数有关呢？
![image](https://user-images.githubusercontent.com/44648619/121481097-5df2c700-c9fe-11eb-9919-9eaf61079af5.png)

**Comment by JunnYu** [comment]
@zyccyz 你可以根据自己需要修改max_position_embeddings长度，原作者chinese_roformer_base这个版本的是在各种句子长度上进行预训练的，最大支持1536，其他型号的模型不清楚作者是否也是在各种长度上训练，保守点，我就设置了512
